Document: ttg
Title: Debian ttg Manual
Author: <insert document author here>
Abstract: This manual describes what ttg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ttg/ttg.sgml.gz

Format: postscript
Files: /usr/share/doc/ttg/ttg.ps.gz

Format: text
Files: /usr/share/doc/ttg/ttg.text.gz

Format: HTML
Index: /usr/share/doc/ttg/html/index.html
Files: /usr/share/doc/ttg/html/*.html
