Document: ttg2
Title: Debian ttg2 Manual
Author: <insert document author here>
Abstract: This manual describes what ttg2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ttg2/ttg2.sgml.gz

Format: postscript
Files: /usr/share/doc/ttg2/ttg2.ps.gz

Format: text
Files: /usr/share/doc/ttg2/ttg2.text.gz

Format: HTML
Index: /usr/share/doc/ttg2/html/index.html
Files: /usr/share/doc/ttg2/html/*.html
