!ifndef DROOT
DROOT = $(MAKEDIR)\..
!endif

# REQUIRED PACKAGES
CONTROLS=Z:\apps\pascal
ARCTL=$(CONTROLS)\arctl\SOURCE
KBMMEMTB=$(CONTROLS)\kbmmemtb253
RX=$(CONTROLS)\RX\Units
UPATH=$(ARCTL);$(KBMMEMTB);$(RX)

# REQUIRED UTILITIES
INNOSETUP="C:\Archivos de programa\Inno Setup 5\COMPIL32.EXE"
DBUTILSSRC=Z:\apps\pascal\DBUTILS\DBUTILS.DPR

# COMPILER OPTIONS
DCC=$(DROOT)\BIN\DCC32.EXE
COMPILE=$(DCC) -U$(UPATH)
UNITS= FMain.pas DMaster.pas KerModel.pas KerEvolE.pas FProgres.pas \
  SortAlgs.pas Rand.pas FCrsMMEd.pas FCrsMME0.pas FCrsMME1.pas FCrsMMER.pas \
  FEditor.pas FMateria.pas FProfesr.pas SGHCUtls.pas FConfig.pas FLogstic.pas \
  FHorPara.pas FMasDeEd.pas FHorAulT.pas FSplash.pas QSingRep.pas QMaDeRep.pas \
  FParalel.pas FSingEdt.pas FHorario.pas About.pas HorColCm.pas FHorProf.pas \
  DSrcBase.pas RelUtils.pas DSource.pas FSelPeIn.pas DBase.pas

# About.pas DMaster.pas FConfig.pas fcrsmme0.pas fcrsmme1.pas \
#   fcrsmmed.pas fcrsmmer.pas feditor.pas fhorario.pas fhorpara.pas fhorprof.pas \
#   flogstic.pas fmain.pas fmasdeed.pas fmateria.pas fparalel.pas fprofesr.pas \
#   fprogres.pas fsingedt.pas fsplash.pas horcolcm.pas kerevole.pas kermodel.pas \
#   qmaderep.pas qsingrep.pas rand.pas sghcutls.pas sortalgs.pas
# DFMS=

all: installer

..\bin\sghc.exe: $(UNITS)
        $(COMPILE) -E..\bin\ SGHC.dpr

..\bin\dbutils.exe:
        $(COMPILE) -E..\bin\ $(DBUTILSSRC)

DSrcBase.pas DSrcBase.dfm: SGHC.MDB ..\bin\dbutils.exe
	..\bin\dbutils.exe /ACC2DM Z:\apps\pascal\SGHC\SOURCE\SGHC.MDB SourceBaseDataModule Z:\apps\pascal\SGHC\SOURCE\DSrcBase /DS

installer:
	cd ..\install
	$(INNOSETUP) /cc sghc.iss
	cd ..\source

clean:
        del *.~*
        del *.dcu
        del *.obj
	del *.exe
        del ..\bin\*.exe
        del install\OUTPUT\*.exe

test:
	echo MAKEDIR=$(MAKEDIR)
